language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
 - composer selfupdate --quiet
 - composer install -n --dev --prefer-source
 - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN="85b84477ccc3a51e2fc6306ffbe8d248a16ca2fda4337b211b35958b5b5e84fe"
  - ./vendor/bin/test-reporter
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email:
    - siad.ardroumli@gmail.com
